---
project_name: epoch

before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/epoch/main.go
    id: "epoch"
    binary: "epoch"
    env:
      - CGO_ENABLED=0
  - main: ./cmd/epoch/main.go
    id: "epoch-full" # Emedding tzdata
    binary: "epoch-full"
    flags:
      - -tags=timetzdata
    env:
      - CGO_ENABLED=0

archives:
  - id: epoch
    builds:
      - epoch
    format: binary
  - id: epoch-full
    builds:
      - epoch-full
    format: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next-{{.Commit}}"

# nfpms:
#   - maintainer: Simon Jürgensmeyyer <simon.juergensmeyer@gmail.com>
#     homepage: https://github.com/sj14/epoch/
#     description: Easily convert epoch timestamps to human readable formats and vice versa.
#     license: MIT
#     formats:
#       - deb
#       - rpm
#       - apk # untested
#     builds:
#       - epoch
#     dependencies:
#       - tzdata

brews:
  - name: epoch
    ids:
      - epoch
    skip_upload: auto
    tap:
      owner: sj14
      name: homebrew-tap
    description: Easily convert epoch timestamps to human readable formats and vice versa.

release:
  github:
    owner: sj14
    name: epoch
  disable: false
  draft: false
  prerelease: auto

changelog:
  filters:
    exclude:
      - typo
