# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: epoch

before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    id: "epoch"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - solaris
      - dragonfly
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - main: ./main.go
    id: "epoch-full" # Emedding tzdata and removing arm build (fails)
    flags:
      - -tags=timetzdata 
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - solaris
      - dragonfly
      - windows
    goarch:
      - 386
      - amd64
      - arm64


archives:
  - id: epoch
    builds:
    - epoch
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
  - id: epoch-full
    builds:
    - epoch-full
    name_template: 
    - "{{ .ProjectName }}-full_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md


checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next-{{.Commit}}"

nfpms:
  - maintainer: Simon Jürgensmeyyer <simon.juergensmeyer@gmail.com>
    homepage: https://github.com/sj14/epoch/
    description: Easily convert epoch timestamps to human readable formats and vice versa.
    license: MIT
    formats:
      - deb
      - rpm
    builds:
      - epoch
    dependencies:
      - tzdata


brews:
  - name: epoch
    ids:
      - epoch
    tap:
      owner: sj14
      name: homebrew-tap
    description: Easily convert epoch timestamps to human readable formats and vice versa.

release:
  github:
    owner: sj14
    name: epoch
  disable: false
  draft: false
  prerelease: false

changelog:
  filters:
    exclude:
      - typo
