language: go
go:
  - 1.x
  - master
env:
  global:
    - GO111MODULE=on
    # - secure: N7GlwGQap3GIr1RDgcaxo02MyiE78YrFRjdzXcPHvd7rkrPDQDOovB+9OVMv/pb4Tlia0Bt+GkcroefwpyLH8BkWyNv+YcNHytz18YVjImZoTN5mvnSX3kWEejX4A8s49FhaAas9aCLcHJAkSkH4hY0O3z9omkqpXp8Ll34rQJtv9TCVq5cJ2xDurraJ4Ld3im70UQbk5dZKsxzWbfBFf69vWtXoIkgOS1GITXwRqvSGgaeiK5HyhQY/wHmT2dZXHHA6vvfZV/cCghmUCoy6IbL26UQIy8vxKgGdYTsswYI89f6xXI8RrW+0S28naS2/GlOryO2JewBMHtKb+ReC8SvVbeTJCDhwMBUEI3vipZvvVNaF2yloAwuIeOkliDsh2+VfLdrqRUdsWQiiHQsYXXNfS2CRj09wWEsdPH6sEo7vndAgenUSmUMtHfDi6CQ9E4smuKb48X694o37WHQW8QtPryIrrCxj2ebKqzJPvM9MRUgRbVfMZ0vmZLyI1EVkPagc2o1k3v/SKANWbV+2x353RucMW5qr1YlntJSruOaO7NFnp0vB7C8BU7FGtivhtMl/gNCDdwXqRJ41V8pOCfA2RUoKqzOjbNJuEo9lgcbUfR15YSekSi2YY1RVD4z2GGnPso1n6BYRXlQVjWq2uu1upYiGIR4AoNyN6/PAPj4= # COVERALLS_TOKEN
matrix:
  allow_failures:
    - go: master
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go get -t -v ./...
  - go vet ./...
  - go test -v -race ./...
  # - go test ./... -v -covermode=count -coverprofile=coverage.out
  # - bash <(curl -s https://codecov.io/bash)
  # - "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN"
